/**
 * Homeopathy
 */
/**
 * All the app constants comes here
 */


//*> CONFIGURATIONS
export const API_TIMEOUT = 30000;

//*> API CALLING CONSTANTS
export const GET_API = 'GET';
export const POST_API = 'POST';
export const PUT_API = 'PUT';
export const DELETE_API = 'DELETE';
export const UPDATE_API = 'PUT';

//*> APP LOADER
export const START_SPINNER = "START_SPINNER"
export const STOP_SPINNER = "STOP_SPINNER"

//*> ERROR MODAL
export const SHOW_ERROR_MODAL = "SHOW_ERROR_MODAL"
export const HIDE_ERROR_MODAL = "HIDE_ERROR_MODAL"

//*> USER CONSTANTS
export const LOGIN_USER = 'LOGIN_USER';
export const SEND_TOKEN = 'SEND_TOKEN';
export const SOCIAL_LOGIN_USER = 'SOCIAL_LOGIN_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const CREATE_GUEST_USER = 'CREATE_GUEST_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const SEND_LINK = 'SEND_LINK';
export const VERIFY_OTP = 'VERIFY_OTP';
export const CONFIRM_ACCOUNT = 'CONFIRM_ACCOUNT';
export const RESEND_CONFIRM_ACCOUNT_TOKEN = 'RESEND_CONFIRM_ACCOUNT_TOKEN';

//*> NOTIFICATIONS DATA CONSTANTS
export const GET_NOTIFICATION_LIST = 'GET_NOTIFICATION_LIST';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const READ_NOTIFICATION = 'READ_NOTIFICATION';
export const READ_ALL_NOTIFICATION = 'READ_ALL_NOTIFICATION';

//*> EXPLORE CONSTANTS
export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST';
export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS';
export const GET_CATEGORY_LIST_FAILURE = 'GET_CATEGORY_LIST_FAILURE';
export const GET_BRAND_LIST = 'GET_BRAND_LIST';
export const GET_BRAND_LIST_SUCCESS = 'GET_BRAND_LIST_SUCCESS';
export const GET_BRAND_LIST_FAILURE = 'GET_BRAND_LIST_FAILURE';
export const GET_TAG_LIST = 'GET_TAG_LIST';
export const GET_TAG_LIST_SUCCESS = 'GET_TAG_LIST_SUCCESS';
export const GET_TAG_LIST_FAILURE = 'GET_TAG_LIST_FAILURE';

//*> PRODUCT CONSTANTS
export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const GET_FILTER_PRODUCT_LIST = 'GET_FILTER_PRODUCT_LIST';
export const GET_PRODUCT_LIST_SUCCESS = 'GET_PRODUCT_LIST_SUCCESS';
export const GET_PRODUCT_LIST_FAILURE = 'GET_PRODUCT_LIST_FAILURE';
export const GET_HOME_PRODUCT_LIST = 'GET_HOME_PRODUCT_LIST';
export const GET_HOME_PRODUCT_LIST_SUCCESS = 'GET_HOME_PRODUCT_LIST_SUCCESS';
export const GET_HOME_PRODUCT_LIST_FAILURE = 'GET_HOME_PRODUCT_LIST_FAILURE';
export const GET_ALL_PRODUCT_LIST = 'GET_ALL_PRODUCT_LIST';
export const GET_ALL_PRODUCT_LIST_SUCCESS = 'GET_ALL_PRODUCT_LIST_SUCCESS';
export const GET_ALL_PRODUCT_LIST_FAILURE = 'GET_ALL_PRODUCT_LIST_FAILURE';
export const GET_RECOMMENDED_PRODUCT_LIST = 'GET_RECOMMENDED_PRODUCT_LIST';
export const GET_RECOMMENDED_PRODUCT_LIST_SUCCESS = 'GET_RECOMMENDED_PRODUCT_LIST_SUCCESS';
export const GET_RECOMMENDED_PRODUCT_LIST_FAILURE = 'GET_RECOMMENDED_PRODUCT_LIST_FAILURE';
export const GET_PRODUCT_DESCRIPTION_LIST = 'GET_PRODUCT_DESCRIPTION_LIST';
export const GET_PRODUCT_DESCRIPTION_LIST_SUCCESS = 'GET_PRODUCT_DESCRIPTION_LIST_SUCCESS';
export const GET_PRODUCT_DESCRIPTION_LIST_FAILURE = 'GET_PRODUCT_DESCRIPTION_LIST_FAILURE';
export const NOTIFY_ME_ABOUT_PRODUCT = 'NOTIFY_ME_ABOUT_PRODUCT';
export const CHECK_PRODUCT_AVAILABILITY = 'CHECK_PRODUCT_AVAILABILITY';
export const GET_HOME_BANNER_LIST = 'GET_HOME_BANNER_LIST';

//*> FILTER DATA CONSTANTS
export const SET_FILTER_DATA = 'SET_FILTER_DATA';
export const REMOVE_FILTER_DATA = 'REMOVE_FILTER_DATA';

//*> SEARCH PRODUCT DATA CONSTANTS
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const SAVE_SEARCH_DETAILS = 'SAVE_SEARCH_DETAILS';
export const GET_RECENT_SEARCH = 'GET_RECENT_SEARCH';

//*> CREATE CART DATA CONSTANTS
export const CREATE_CART = 'CREATE_CART';
export const CREATE_CART_SUCCESS = 'CREATE_CART_SUCCESS';
export const CREATE_CART_FAILURE = 'CREATE_CART_FAILURE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_QUANTITY_IN_CART = 'UPDATE_QUANTITY_IN_CART';
export const ADD_ADDRESS_TO_ORDER = 'ADD_ADDRESS_TO_ORDER';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CART_HAS_PRODUCT = 'CART_HAS_PRODUCT';
export const CART_HAS_PRODUCT_SUCCESS = 'CART_HAS_PRODUCT_SUCCESS';
export const CART_HAS_PRODUCT_FAILURE = 'CART_HAS_PRODUCT_FAILURE';
export const SHOW_CART_DATA = 'SHOW_CART_DATA ';
export const APPLY_COUPON = 'APPLY_COUPON ';
export const REMOVE_COUPON = 'REMOVE_COUPON ';
export const CHECK_ORDER_ITEM_AVAILABILITY = 'CHECK_ORDER_ITEM_AVAILABILITY ';
export const RELEASE_MY_BLOCK_QUANTITY = 'RELEASE_MY_BLOCK_QUANTITY ';
export const PLACE_ORDER = 'PLACE_ORDER ';
export const MY_ORDER_LIST = 'MY_ORDER_LIST ';
export const GET_TRACK_ID_DETAILS = 'GET_TRACK_ID_DETAILS ';
export const GET_REVIEW_LIST = 'GET_REVIEW_LIST ';
export const SUBMIT_ORDER_REVIEW = 'SUBMIT_ORDER_REVIEW ';
export const BUY_PRODUCT = 'BUY_PRODUCT ';
export const CANCEL_ORDER = 'CANCEL_ORDER ';
export const GET_LOGISTIC_TRACK_ID_DETAILS = 'GET_LOGISTIC_TRACK_ID_DETAILS ';
export const UPDATE_CART_DATA = 'UPDATE_CART_DATA';

//*> CREATE CART DATA CONSTANTS
export const GET_PROFILE_DATA = 'GET_PROFILE_DATA';
export const GET_PROFILE_DATA_SUCCESS = 'GET_PROFILE_DATA_SUCCESS';
export const GET_PROFILE_DATA_FAILURE = 'GET_PROFILE_DATA_FAILURE';
export const UDPATE_PROFILE_DATA = 'UDPATE_PROFILE_DATA';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';

//*> ADDRESS LIST DATA CONSTANTS
export const GET_HELP_CENTER_DETAILS = 'GET_HELP_CENTER_DETAILS';
export const SAVE_CONTACT_US_DETAILS = 'SAVE_CONTACT_US_DETAILS'

//*> SOCIAL MEDIA DATA CONSTANTS
export const GET_FAQ_LIST = 'GET_FAQ_LIST';

//*> SOCIAL MEDIA DATA CONSTANTS
export const GET_SOCIAL_MEDIA_ACCOUNT_DETAILS = 'GET_SOCIAL_MEDIA_ACCOUNT_DETAILS';
export const ADD_SOCIAL_MEDIA_ACCOUNT_DETAILS = 'ADD_SOCIAL_MEDIA_ACCOUNT_DETAILS';
export const REMOVE_SOCIAL_MEDIA_ACCOUNT_DETAILS = 'REMOVE_SOCIAL_MEDIA_ACCOUNT_DETAILS';

//*> ADDRESS LIST DATA CONSTANTS
export const GET_ADDRESS_LIST = 'GET_ADDRESS_LIST';
export const CREATE_ADDRESS = 'CREATE_ADDRESS';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';


//*> WISHLIST DATA CONSTANTS
export const GET_WISHLIST = 'GET_WISHLIST';
export const GET_WISHLIST_SUCCESS = 'GET_WISHLIST_SUCCESS';
export const GET_WISHLIST_FAILURE = 'GET_WISHLIST_FAILURE';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';


//*> PAYMENT DATA CONSTANTS
export const PAYMENT_REDIRECTION = "PAYMENT_REDIRECTION";
export const PAYMENT_AUTHORIZATION = "PAYMENT_AUTHORIZATION";
export const PAYMENT_CAPTURE = "PAYMENT_CAPTURE";
export const PAYMENT_CONFIRM_ORDER = "PAYMENT_CONFIRM_ORDER";